[MongoDB]
DbURL = "localhost:27917"
DbName = "testdb"
UserName = "test"
Password = "test"

[SrcToken]
BlockChain = "Bitcoin"
NetID = "TestNet3"
Name = "Bitcoin Coin"
Symbol = "BTC"
Decimals = 8
Description = "Bitcoin Coin"
DcrmAddress = "2MvK2LXz2jqE3tLFhU4dLb7SCWf2orPMvyF"
Confirmations = 6
MaximumSwap = 1000.0
MinimumSwap = 0.0004
SwapFeeRate = 0.001

[SrcGateway]
ApiAddress = "http://47.107.50.83:3002"

[DestToken]
BlockChain = "Ethereum"
NetID = "Rinkeby"
Name = "SMPC Bitcoin"
Symbol = "mBTC"
Decimals = 8
Description = "cross chain bridge BTC with mBTC"
ContractAddress = "0x26e3AB5f1930A0E4A75421743Eb11f298691675D"
DcrmAddress = "0x2bac00388caa75edcc53a2bd329f7e9563c6acb6"
Confirmations = 33
MaximumSwap = 100.0
MinimumSwap = 0.0004
SwapFeeRate = 0.001

[DestGateway]
ApiAddress = "http://5.189.139.168:8018"

[ApiServer]
Port = 11556

[Dcrm]
RpcAddress="http://127.0.0.1:9011"

GroupID="6ab4f2a681bd73ba6328aaf196e19c62723f59c847b0a5cda93665dd610ac2cf87f0608ef5ea7f0c8368da62699ee4bf8eec8b33270b546e5481df1c99e05857"

# NeededOracles=2,TotalOracles=3 represent '2/3' threshold
NeededOracles=2
TotalOracles=3

# 0:managed 1:private
Mode=0

Pubkey="04908094331606866ee248bf9a802a2a881ab519ac1daf411ab8a69d2ba08af02ab413b93dba8eefacb8d4608b1c53fdf291a6f9b96b468e878fc4e851ecc34a2d"
KeystoreFile="node1/keystore/keystore1"
PasswordFile="password.txt"
