[MongoDB]
DbURL = "localhost:27917"
DbName = "testdb"
UserName = "test"
Password = "test"

[SrcToken]
BlockChain = "Bitcoin"
NetID = "TestNet3"
Name = "Bitcoin Coin"
Symbol = "BTC"
Decimals = 8
Description = "Bitcoin Coin"
DcrmAddress = "2MvK2LXz2jqE3tLFhU4dLb7SCWf2orPMvyF"
Confirmations = 6
MaximumSwap = 1000.0
MinimumSwap = 0.0004
SwapFeeRate = 0.001

[SrcGateway]
ApiAddress = "http://localhost:11001"

[DestToken]
BlockChain = "Ethereum"
NetID = "Rinkeby"
Name = "BTC Swap Asset"
Symbol = "mBTC"
Decimals = 8
Description = "cross chain bridge BTC with mBTC"
ContractAddress = "0x26e3AB5f1930A0E4A75421743Eb11f298691675D"
Confirmations = 33
MaximumSwap = 100.0
MinimumSwap = 0.0004
SwapFeeRate = 0.001

[DestGateway]
ApiAddress = "http://localhost:12001"

[ApiServer]
Port = 11556
